services:
  postgres:
    container_name: atlas-postgres
    image: postgres:14
    restart: always
    volumes:
      - atlas:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  atlas: